# Упражнения "Работа с тензорами в PyTorch"

Задание 1. Импортируйте PyTorch и посмотрите версию.

In [29]:
import torch

In [30]:
print(torch.__version__)


2.9.0+cpu


Задание 2. Создайте одномерный тензор чисел от 0 до 9.

Желаемый результат:

> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
tens = torch.tensor([0,1,2,3,4,5,6,7,8,9])
print(tens)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Задание 3. Для тензора, созданного в задании 2, выведите


*   тип элементов
*   размер
*   количество размерностей



In [32]:
print(f"тип элементов: {tens.dtype}")
print(f"размер: {tens.shape}")
print(f"количество размерностей: {tens.dim()}")

тип элементов: torch.int64
размер: torch.Size([10])
количество размерностей: 1


Задание 4. Разделите тензор из задания 2 на две половины (левую - начало тензора и правую - его конец). Выведите обе эти половины.

In [33]:
tens_left = tens[:5]
tens_right = tens[5:]
print(tens_left,tens_right)


tensor([0, 1, 2, 3, 4]) tensor([5, 6, 7, 8, 9])


Задание 5. Создайте вещественный массив размером $3 \times 4$, в котором все элементы равны 1.

In [34]:
torch.ones(3,4)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Задание 6. Создайте логический массив размером $5 \times 2$, в котором все элементы равны True.

In [35]:
torch.ones(5,2,dtype=torch.bool)



tensor([[True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True]])

Задание 7. Создайте одномерный тензор с последовательностью вещественных чисел от 1 до 15 включительно, в котором каждый следующий элемент отличается от предыдущего на 0.5

In [36]:
torch.tensor([i/2 for i in range(2,31)])

tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000, 10.5000, 11.0000, 11.5000, 12.0000, 12.5000,
        13.0000, 13.5000, 14.0000, 14.5000, 15.0000])

Задание 8. Создайте одномерный тензор, в котором ровно 20 значений. Первой значение 1, последнее значение 10, а расстояние между каждыми двумя соседними элементами одинаково.

In [56]:
torch.linspace(1, 10, 20, dtype=torch.float64)


tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000], dtype=torch.float64)

Задание 9. Создайте двумерный тензор случайных вещественных значений размером $4 \times 3$ из равномерного распределения на полуинтервале [0, 1).

In [38]:
torch.rand(4,3,dtype= torch.float32)


tensor([[0.7331, 0.3654, 0.6513],
        [0.8535, 0.6701, 0.1043],
        [0.2979, 0.8284, 0.2787],
        [0.9470, 0.4785, 0.5198]])

Задание 10. Создайте одномерный тензор 100 случайных "школьных оценок", а именно целых значений из промежутка от 3 до 5 включительно.

In [39]:
score = torch.randint(3,6,(1,100))
score_vector = torch.tensor(score[0],dtype=torch.int)
print(score_vector)

tensor([5, 4, 4, 5, 5, 4, 5, 4, 4, 4, 5, 3, 4, 4, 3, 5, 3, 3, 4, 3, 3, 4, 3, 4,
        4, 4, 3, 3, 5, 3, 5, 3, 4, 3, 3, 5, 3, 5, 4, 5, 5, 3, 3, 4, 3, 4, 3, 4,
        4, 3, 5, 4, 4, 3, 5, 3, 4, 5, 3, 3, 3, 4, 4, 3, 5, 4, 5, 3, 3, 3, 3, 5,
        4, 4, 5, 4, 4, 3, 4, 5, 4, 3, 3, 4, 5, 4, 4, 3, 5, 3, 4, 3, 4, 4, 3, 5,
        4, 3, 3, 5], dtype=torch.int32)


/tmp/ipython-input-1405029186.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  score_vector = torch.tensor(score[0],dtype=torch.int)


Задание 11. Для тензора "школьных отенок", созданного в задании 10, посчитайте и выведите минимум, максимум и среднее арифметическое.

In [40]:
print(f"Минимальное значение:{score_vector.min()}")
print(f"Максимальное значение: {score_vector.max()}")
print(f"Среднее арифметическое элементов: {score_vector.float().mean()}")


Минимальное значение:3
Максимальное значение: 5
Среднее арифметическое элементов: 3.859999895095825


Задание 12. Создайте создайте булеву маску для массива "школьных оценок" из задания 10, в которой True будет стоять для первых 5 оценок и для последних 5 оценок, а остальные значения будут False.

In [41]:
mask = torch.zeros_like(score_vector, dtype=torch.bool)

mask[:5] = 1
mask[5:95] = 0
mask[95:] = 1
print(mask)

tensor([ True,  True,  True,  True,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True,  True,  True,  True,  True])


In [42]:
score_vector[mask]

tensor([5, 4, 4, 5, 5, 5, 4, 3, 3, 5], dtype=torch.int32)

Задание 13. Отфильтруйте тензор "школьных оценок", созданный в задании 10, с помощью маски, созданной в задании 12, оставив тем самым только первые и последние пять оценок.

In [43]:
score_vector[mask]


tensor([5, 4, 4, 5, 5, 5, 4, 3, 3, 5], dtype=torch.int32)

Задание 14. Создайте маску для тензора "школьных оценок", в которой для каждой "пятерки" будет стоять True, а для остальных значений будет стоять False.

In [44]:
mask_2 = torch.zeros_like(score_vector, dtype=torch.int)
mask_2 = (mask_2 + score_vector//5).bool()
print(mask_2)


tensor([ True, False, False,  True,  True, False,  True, False, False, False,
         True, False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False,  True, False,
         True, False, False, False, False,  True, False,  True, False,  True,
         True, False, False, False, False, False, False, False, False, False,
         True, False, False, False,  True, False, False,  True, False, False,
        False, False, False, False,  True, False,  True, False, False, False,
        False,  True, False, False,  True, False, False, False, False,  True,
        False, False, False, False,  True, False, False, False,  True, False,
        False, False, False, False, False,  True, False, False, False,  True])


Задание 15. Извлеките все "пятерки" из тензора "школьных отенок", созданного в задании 10, и занесите их в новый тензор.


In [45]:
new_score = score_vector[mask_2]
print(new_score)

tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       dtype=torch.int32)


Задание 16. Преобразуйте тензор "школьных оценок" в двумерный тензор с 5 строками размером $5 \times 20$.


In [46]:
score_vector = score_vector.reshape(5,20)
print(score_vector)

tensor([[5, 4, 4, 5, 5, 4, 5, 4, 4, 4, 5, 3, 4, 4, 3, 5, 3, 3, 4, 3],
        [3, 4, 3, 4, 4, 4, 3, 3, 5, 3, 5, 3, 4, 3, 3, 5, 3, 5, 4, 5],
        [5, 3, 3, 4, 3, 4, 3, 4, 4, 3, 5, 4, 4, 3, 5, 3, 4, 5, 3, 3],
        [3, 4, 4, 3, 5, 4, 5, 3, 3, 3, 3, 5, 4, 4, 5, 4, 4, 3, 4, 5],
        [4, 3, 3, 4, 5, 4, 4, 3, 5, 3, 4, 3, 4, 4, 3, 5, 4, 3, 3, 5]],
       dtype=torch.int32)


Задание 17. Выполните стыковку тензоров a и b по вертикали.

Вход:

> a = torch.arange(2, 10, 2).reshape(2, -1)

> b = torch.repeat(1, 10).reshape(2, -1)

Желаемый результат: новый тензор размером $4 \times 5$.


In [47]:
a = torch.arange(2, 22, 2).reshape(2, -1)
b = torch.arange(1, 21, 2).reshape(2, -1)
c1 = torch.cat([a, b], dim=0)
print(c1)

tensor([[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20],
        [ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19]])


Задание 18. Выполните стыковку тензоров a и b по горизонтали.

Вход:

a = torch.arange(2, 10, 2).reshape(2, -1)

b = torch.repeat(1, 10).reshape(2, -1)

Желаемый результат: новый тензор размером $2 \times 10$.

In [48]:
a = torch.arange(2, 22, 2).reshape(2, -1)
b = torch.arange(1, 21, 2).reshape(2, -1)
c2 = torch.cat([a, b], dim=1)
print(c2)

tensor([[ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9],
        [12, 14, 16, 18, 20, 11, 13, 15, 17, 19]])


Задание 19. Получите все элементы от 5 до 10 в тензоре a.

Вход:

> a = torch.tensor([2, 6, 1, 9, 10, 3, 27])

Желаемый результат:

> tensor([6, 9, 10])

In [49]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
print(a[(a>5) &(a<=10)])

tensor([ 6,  9, 10])


Задание 20. Вывести первую строку матрицы из задания 18.

In [50]:
c2[0,:]

tensor([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

Задание 21. Вывести последний столбец матрицы из задания 17.

In [51]:
c1[:,-1]

tensor([10, 20,  9, 19])

Задание 22. Вывести центральную часть матрицы из задания 17 (размерностью $2 \times 3$).

In [52]:
c1[1:3,1:4]

tensor([[14, 16, 18],
        [ 3,  5,  7]])

Задание 23. Вставить в двумерный терзор из задания 17 строку из минимального элемента перед первой строкой.

In [53]:
min = c1[0].min()
row = torch.ones(1, 5)*min
c3 = torch.cat([row, c1], dim=0)
c3

tensor([[ 2.,  2.,  2.,  2.,  2.],
        [ 2.,  4.,  6.,  8., 10.],
        [12., 14., 16., 18., 20.],
        [ 1.,  3.,  5.,  7.,  9.],
        [11., 13., 15., 17., 19.]])

Задание 24.	В тензоре, полученном при выполнении задания 23, каждый элемент заменить его корнем квадратным.

In [54]:
c3.sqrt()

tensor([[1.4142, 1.4142, 1.4142, 1.4142, 1.4142],
        [1.4142, 2.0000, 2.4495, 2.8284, 3.1623],
        [3.4641, 3.7417, 4.0000, 4.2426, 4.4721],
        [1.0000, 1.7321, 2.2361, 2.6458, 3.0000],
        [3.3166, 3.6056, 3.8730, 4.1231, 4.3589]])

Задание 25.	Заменить в тензоре из задания 18 все значения, кратные 3 или 2 на число 1, а остальные – оставить без изменений.

In [55]:
print(c2)
c2[(c2% 2 == 0) | (c2 % 3 == 0)] = 1
print(c2)

tensor([[ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9],
        [12, 14, 16, 18, 20, 11, 13, 15, 17, 19]])
tensor([[ 1,  1,  1,  1,  1,  1,  1,  5,  7,  1],
        [ 1,  1,  1,  1,  1, 11, 13,  1, 17, 19]])
